project:
  type: website

website:
  title: "STAT 133"
  favicon: assets/stat133-hex-logo.png
  google-analytics: G-CES9J82GLL
  page-footer: 
    center:
      - text: About
        href: info/about.qmd
      - text: License
        href: info/license.qmd
    background: "dark"
  sidebar:
    style: "docked"
    title: "STAT 133 <br><small>Spring 2026</small>"
    logo: assets/stat133-hex-logo-small.png
    logo-alt: "UC Berkeley Statistics logo"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - href: officehours.qmd
        text: "Office Hours"
      - cheatsheets.qmd
      - section: "More"
        contents:
          - info/about.qmd
          - href: info/faqs.qmd
            text: "FAQs"
          - info/license.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    fontsize: 1.0em
    grid: 
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 300px
    css: styles.css
    toc: true
    link-external-newwindow: true # opens links in new tab
